src/Entity/Product.php
<?php

namespace App\Entity;

use AllowDynamicProperties;
use App\Repository\ProductRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\UploadedFile;

#[ORM\Entity(repositoryClass: ProductRepository::class)]
#[AllowDynamicProperties]
class Product
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(length: 255)]
    private ?string $description = null;

    #[ORM\Column(length: 255)]
    private null|UploadedFile|string $photo_name = null;

    #[ORM\ManyToOne(inversedBy: 'products')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Category $category = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 5, scale: 2)]
    private ?string $price = null;

    #[ORM\Column]
    private ?int $quantity = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function setId(int $id): static
    {
        $this->id = $id;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getPhotoName(): null|string|UploadedFile
    {
        return $this->photo_name;
    }

    public function setPhotoName(null|string|UploadedFile $photo_name): static
    {
        $this->photo_name = $photo_name;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): static
    {
        $this->category = $category;

        return $this;
    }

    public function getPrice(): ?string
    {
        return $this->price;
    }

    public function setPrice(string $price): static
    {
        $this->price = $price;

        return $this;
    }

    public function getQuantity(): ?int
    {
        return $this->quantity;
    }

    public function setQuantity(int $quantity): static
    {
        $this->quantity = $quantity;

        return $this;
    }
}

src/Controller/Admin/ProductController.php
<?php

namespace App\Controller\Admin;

use App\Entity\Product;
use App\Form\ProductFormType;
use App\Repository\ProductRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\HttpFoundation\RequestStack;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\String\ByteString;

#[Route('/my-admin')]
class ProductController extends AbstractController
{

    public function __construct(
        private ProductRepository $productRepository, 
        private RequestStack $requestStack,
        private EntityManagerInterface $entityManagerInterface
        ) {
    
    }

    #[Route('/products', name: 'app_admin_product')]
    public function index(): Response
    {

        return $this->render('admin/product/index.html.twig', [
            'products' => $this->productRepository->findAll(),
        ]);
    }


        #[Route('/products/delete{id}', name: 'app_admin_delete_product')]
    public function delete(int $id): Response
    {
        if ($id != null) {
            $current_product = $this->productRepository->find($id);
        }
        if (!$current_product) {
            $this->addFlash('danger', 'Le produit indexé est unexistant !');
            return $this->redirectToRoute('app_admin_product');
        }

        $this->entityManagerInterface->remove($current_product);
            $this->entityManagerInterface->flush();

                if($id) {
                    unlink("img/{$current_product->getPhotoName()}");
                }

        $this->addFlash('success', 'Le produit a été supprimé avec succès !');
        return $this->redirectToRoute('app_admin_product');

    }

    #[Route('/products/form', name: 'app_admin_product_form')]
    #[Route('/products/update/{id}', name: 'app_admin_edit_product_form')]
    public function form(int $id = null): Response
    {

        if ($id != null) {
            $current_product = $this->productRepository->find($id);
        }
        
        $entity = ($id!= null && $current_product) ? $current_product : new Product();

        if ($id!= null && $current_product == null) {
            $this->addFlash('danger', 'Le produit indexé n\'existe pas !');
            return $this->redirectToRoute('app_admin_product');
        }

        $entity->prevPhotoName = $entity->getPhotoName();


        $type = ProductFormType::class;
        $form = $this->createForm($type, $entity);

        $form->handleRequest($this->requestStack->getMainRequest());

        if($form->isSubmitted() && $form->isValid()){
            // dd($entity);
            $filename = ByteString::fromRandom(16)->lower();


            $file = $entity->getPhotoName();

            if($file instanceof UploadedFile){
                $fileExtension = $file->guessClientExtension();
                $file->move('img', "$filename.$fileExtension");

                $entity->setPhotoName("$filename.$fileExtension");

                if($id) {
                    unlink("img/{$entity->prevPhotoName}");
                }
            } else {
                 $entity->setPhotoName($entity->prevPhotoName);
            }



            // dd($filename, $entity);



            $this->entityManagerInterface->persist($entity);
            $this->entityManagerInterface->flush();

            $this->addFlash('success', ($id!= null && $current_product) ? 'Produit modifié avec succès !' :'Produit créé avec succès !');
            return $this->redirectToRoute('app_admin_product');
        }

        return $this->render('admin/product/form.html.twig', [
            'form' => $form->createView(),
        ]);
    }
}

src/Controller/ProductController.php
<?php

namespace App\Controller;

use App\Entity\Product;
use App\Form\ProductFormType;
use App\Repository\ProductRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\RequestStack;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class ProductController extends AbstractController
{

    public function __construct(private ProductRepository $productRepository,)
    {
    }

    #[Route('/products', name: 'products.index')]
    public function index(): Response
    {
        $products = $this->productRepository->findAll();
        //dd($products);
        return $this->render('products/index.html.twig', [
            'products' => $products,
        ]);
    }

    #[Route('/products/add', name: 'products.add')]

    public function add(): Response
    {
        $form = $this->createForm(ProductFormType::class);

        return $this->render('products/add.html.twig', [
            'form' => $form,
        ]);
    }

    #[Route('/products/{id}', name: 'products.show')]
    public function show(int $id = null): Response
    {
        $product = $this->productRepository->find($id);
        // dd($product);
        return $this->render('products/show.html.twig', [
            'product' => $product,
        ]);
    }
}

templates/products/add.html.twig
{% extends "base.html.twig" %} {% block body %} {{ form(form)}} {# {{ form_start(form) }} {{ form_label(form.name) }} {{ form_widget(form.description) }} {{ form_label(form.price) }} {{ form_widget(form.photo_name) }} {{ form_widget(form.category)}} {{form_rest(form)
}}
<button type="submit">Enregistrer</button> {{ form_end(form) }} #} {% endblock %}

templates/products/index.html.twig
{% extends 'base.html.twig' %} {% block body %}

<head>

    {% block extra_css %}
    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
        }
        
        @media(min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }
    </style>


    {% endblock %}


    <!-- Custom styles for this template -->
    <link href="https://fonts.googleapis.com/css?family=Playfair+Display:700,900" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="blog.css" rel="stylesheet">
</head>

<body>
    <div class="container">

        <div class="nav-scroller py-1 mb-2">
            <nav class="nav d-flex justify-content-between">
                <a class="p-2 text-muted" href="#">Tech</a>
                <a class="p-2 text-muted" href="#">Art</a>
                <a class="p-2 text-muted" href="#">Culture</a>
                <a class="p-2 text-muted" href="#">Business</a>
            </nav>
        </div>

        <!-- <div class="jumbotron p-3 p-md-5 text-white rounded bg-dark mb-4">
						            <div class="col-md-6 px-0">
						                <h1 class="display-4 font-italic">All our products</h1>
						                <p class="lead my-3">Explore our diverse range of high-quality products, meticulously crafted to meet your needs. From cutting-edge technology to timeless classics, our product page offers a curated selection that combines innovation with style.</p>
						                <p class="lead mb-0">
						                    <a href="#" class="text-white font-weight-bold">Continue reading...</a>
						                </p>
						            </div>
						        </div> -->

        <div class="my-4" style="text-align: right;">
            <a href="{{ url('products.add') }}" class="btn btn-dark">Add  
					<i class="fa-solid fa-plus"></i>
				</a>

        </div>


        <div class="row mb-2">

            {% for product in products %}
            <div class="col-md-6">
                <div class="card flex-md-row mb-4 shadow-sm h-md-250">
                    <div class="card-body d-flex flex-column col-md-6 align-items-start">
                        <strong class="d-inline-block mb-2 text-primary">{{product.category.name}}</strong>
                        <h3 class="mb-0">
                            <a class="text-dark" href="#">{{product.name}}</a>
                        </h3>
                        <div class="mb-1 text-muted">{{product.price | format_currency('EUR', locale='fr') | replace({',00' : ''})}}</div>
                        <p class="card-text mb-auto">{{product.description}}</p>
                        <a class="btn btn-outline-primary" href="{{ url('products.show',  { id : product.id}) }}">Details</a>
                    </div>

                    <div class="bd-placeholder-img card-img-right col-md-6 flex-auto d-none d-lg-block">
                        <img class="img-thumbnail" style="height: 100%;" src="{{ asset('img/' ~ product.photoName) }}" alt="Product">
                    </div>
                </div>
            </div>
            {% endfor %}

        </div>

    </div>


    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script>
        window.jQuery || document.write('<script src="/docs/4.2/assets/js/vendor/jquery-slim.min.js"><\/script>')
    </script>
    <script src="/docs/4.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-zDnhMsjVZfS3hiP7oCBRmfjkQC4fzxVxFhBx8Hkz2aZX8gEvA/jsP3eXRCvzTofP" crossorigin="anonymous"></script>

</body>

{% endblock %}

templates/products/show.html.twig
{% extends "base.html.twig" %} {% block body %}
<div class="jumbotron my-4 text-center">
    <h1 class="display-4">Details of {{ product.name }}</h1>
    <p>
        {{ product.quantity == 0 ? 'unavailable product' : 'Quantity: ' ~ product.quantity }}
    </p>
    <center>
        <p class="lead">
            <div style="display: flex; max-width: 20%; text-align: center;" class="bd-placeholder-img card-img-right col-md-6 flex-auto d-none d-lg-block">

                <img class="img-thumbnail" style="height: 10%;" src="{{ asset('img/' ~ product.photoName) }}" alt="Product">

            </div>
        </p>
    </center>
    <hr class="my-4">
    <p>{{ product.description }}</p>
    <a href="/products" role="button">Retour</a>
</div>

{% endblock %}